version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  rebase-strategy: auto
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  rebase-strategy: auto
- package-ecosystem: cargo
  directory: "/native"
  schedule:
    interval: daily
  rebase-strategy: auto
