pipeline {
  agent { label 'docker' }

  options {
    timeout(time: 20, unit: 'MINUTES')
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }

  stages {
    stage('Build Rust') {
      agent {
        docker {
          image 'sub-planpro-rust-mingw'
          reuseNode true
        }
      }

      steps {
        container('rust') {
          dir('cef/Release') {
            downloadCEF versionFile: '../../CEF_VERSION.txt', files: ['Release/libcef.lib']
          }

          sh 'rustup target add x86_64-pc-windows-gnu'
          dir('native') {
            sh 'cargo clean'
            sh 'cargo build --release --target x86_64-pc-windows-gnu'

            sh 'cargo tree --prefix none --locked --frozen --no-dedupe | sort -u | grep -v \'(\' | sed \'s|\\(.*\\) v\\([0-9]*\\.[0-9]*\\.[0-9]*\\)|crate/cratesio/-/\\1/\\2|g\' > rust.deps'
            stash name: 'rust_dependencies', includes: 'rust.deps', useDefaultExcludes: false
          }

          dir('native/target/x86_64-pc-windows-gnu/release') {
            stash name: 'rust_binaries', includes: 'chromium_subp.exe, chromium_jni.dll', useDefaultExcludes: false
          }
        }
      }
    }

    stage('Build Java') {
      agent {
        docker {
          image 'sub-planpro-java'
          reuseNode true
        }
      }

      steps {
        container('maven') {
          dir('java/org.eclipse.set.browser.lib/res') {
            unstash 'rust_binaries'
          }

          dir('java') {
            mvn goal: 'clean verify'
          }
        }
      }
    }

    stage('Deploy Snapshot') {
      agent {
        docker {
          image 'sub-planpro-java'
          reuseNode true
        }
      }

      when {
        anyOf {
          buildingTag()
          branch 'main'
          branch pattern: 'release/[0-9.]+', comparator: 'REGEXP'
          branch pattern: 'feature/\\w+', comparator: 'REGEXP'
        }
      }

      steps {
        deployP2Site name: 'browser', path: 'java/org.eclipse.set.browser.releng.repository/target/repository'
      }
    }
  }

  post {
    always {
      // Publish JUnit test result
      junit testResults: 'java/*/target/surefire-reports/*.xml', allowEmptyResults: true
      recordIssues aggregatingResults: true,
        enabledForFailure: true,
        tools: [
          checkStyle(),
          mavenConsole()],
        qualityGates: [[threshold: 1, type: 'TOTAL', unstable: true]]
    }
  }
}
