pipeline {
  agent {
    kubernetes {
      yamlFile 'ci/kubernetes.yaml'
    }
  }

  options {
    timeout(time: 20, unit: 'MINUTES')
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }

  stages {
    stage('Build') {
      steps {
        container('rust') {
          dir('cef/Release')
          {
            script {
              def version = sh (script: "grep -E -v ^# ../../CEF_VERSION.txt", returnStdout: true).trim()
              sh (script: "curl -o 'cef.tar.bz2' https://cef-builds.spotifycdn.com/${version}.tar.bz2")
              sh (script: "tar xf cef.tar.bz2 ${version}/Release/libcef.lib --strip-components 2")
              sh (script: 'rm -rf cef.tar.bz2')
            }
          }

          sh 'rustup target add x86_64-pc-windows-gnu'
          dir('native')
          {
            sh 'cargo clean'
            sh 'cargo build --release --target x86_64-pc-windows-gnu'
          }
        }

        container('maven') {
          // copy rust binaries to target location
          sh 'mkdir -p java/org.eclipse.set.browser.lib/res'
          sh 'cp -r native/target/x86_64-pc-windows-gnu/release/chromium_subp.exe java/org.eclipse.set.browser.lib/res/'
          sh 'cp -r native/target/x86_64-pc-windows-gnu/release/chromium_jni.dll java/org.eclipse.set.browser.lib/res/'

          dir('java')
          {
            sh "mvn -U -B clean integration-test"
          }
        }
      }
    }

    stage('Deploy Snapshot')
    {
      when {
        branch 'main'
      }
      steps {
        container('jnlp') {
          sshagent (['projects-storage.eclipse.org-bot-ssh']) {
            sh 'ssh -o BatchMode=yes genie.set@projects-storage.eclipse.org rm -rf /home/data/httpd/download.eclipse.org/set/snapshots/browser'
            sh 'ssh -o BatchMode=yes genie.set@projects-storage.eclipse.org mkdir -p /home/data/httpd/download.eclipse.org/set/snapshots/browser'
            sh 'scp -o BatchMode=yes -r java/org.eclipse.set.browser.releng.repository/target/repository/* genie.set@projects-storage.eclipse.org:/home/data/httpd/download.eclipse.org/set/snapshots/browser'
          }
        }
      }
    }
  }
}