[package]
name = "chromium_subp"
version = "1.0.0"
authors = ["Equo <https://www.equoplatform.com/>", "Guillermo Zunino <guillez@gmail.com>"]
edition = "2021"

[[bin]]
name = "chromium_subp"
path = "src/bin/chromium_subp.rs"

[dependencies]
chromium = { path = "../chromium/" }
winapi = { version = "0.3.9", features = ["winuser", "libloaderapi"] }

[lints.clippy]
missing_safety_doc = "allow"
not_unsafe_ptr_arg_deref = "allow"
too_many_arguments = "allow"